### ISSUE TITLE
Move the `EnableWebsockets` to vaadin-quarkus-extension

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-quarkus#19]
The `EnableWebsockets` class is an internal Quarkus+Vaadin integration class and should be therefore present in vaadin-quarkus-extension, rather than in every Vaadin Quarkus project.

**Comment by mvysny** [comment]
Created PR: https://github.com/urosporo/vaadin-quarkus-extension-parent/pull/11

**Comment by mbrem** [comment]
It's merged and in released: 1.0.0-RC3

**Comment by mvysny** [comment]
Perfect, thank you @mbrem
